config/routes.rb
Rails.application.routes.draw do

  get 'reviews/index'

  get 'bookings/:id/index', to: 'bookings#index'
  get 'users/index'
  post 'users/:id/destroy_user', to:'users#destroy_user'
  post 'reviews/add_review'
  post 'reviews/:id/destroy',to: 'reviews#destroy'
  get 'hotels/home'
  root 'hotels#home'
  post '/rate' => 'rater#create', :as => 'rate'
  resources :profiles
  devise_for :users
  resources :rooms do
    get 'bookings/:id/new', to:'bookings#new'
    post 'bookings/:user_id/create', to: 'bookings#create'
    get 'roompictures/index'
    post 'roompictures/add_picture'
    post 'roompictures/:id/remove_picture/', to: 'roompictures#remove_picture'
    post 'roompictures/create'
    post 'roompictures/destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :roooms
	ratyrate_rateable "ratings"
	has_many :reviews, dependent: :delete_all
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :hotel
	has_many :roompictures, dependent: :delete_all
	has_many :users, through: :bookings	
end

app/models/roompicture.rb
class Roompicture < ApplicationRecord
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
  has_many :reviews, dependent: :delete_all
  has_one :profile, dependent: :delete

  has_many :rooms, through: :bookings
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roompictures_helper.rb
module RoompicturesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="margin-bottom: 0px; background-color: rgb(240,240,240); ">
       <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <li class="navbar-brand" style="background-image: url(/images/logo.jpeg); width: 50px;height: 50px;margin-right: 10px"></li>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse pull-left navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to "Home",hotels_home_path,class: "navbar-brand topnav" %>
                </li>
                <li>
                    <% if current_user.present? %>
                    <% if current_user.profile.present? %>
                    <%= link_to "Profile",profile_path(current_user.id),class: "navbar-brand topnav"%>
                    <% else %>
                    <%= link_to "Create Profile",new_profile_path,class: "navbar-brand topnav"%>
                    <% end %>
                    <% end %>
                </li>
                <li>
                    <%= link_to "Rooms",rooms_path,class: "navbar-brand topnav" %>
                </li>
                <li>
                    <%= link_to "Reviews",reviews_index_path,class: "navbar-brand topnav" %>
                </li>
                <li>
                  <% if current_user.present? %>
                  <% if current_user.is_admin? %>
                  <%= link_to "Users",users_index_path,class: "navbar-brand topnav" %>
                  <% end %>
                  <% end %>
              </li>
              <li>
                <% if current_user.present? %>
                <%= link_to "Sign Out",destroy_user_session_path, method: 'delete',class: "navbar-brand topnav"  %>
                <% else %>
                <%= link_to "Sign In",new_user_session_path,class: "navbar-brand topnav"  %>
                <% end %>
            </li>
            
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</div>
<!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CloudProject</title>
	<%= csrf_meta_tags %>
	<%= cloudinary_js_config %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<%= render 'layouts/nav' %>
	<div class="container center">
		<div class="row" style="margin-top: 5%">
			<div class="col-lg-12 col-xs-12 col-sm-12 col-md-12 text-center">
				<%= yield %>
			</div>
		</div>
	</div>
	<div style="height:20px"></div>
	<footer style="height: 70px; margin:0; clear:both; width: 100%;  position: relative; background-color: rgb(240,240,240);">
		<div class="container">
			<h4>PC Hotel</h4>
			<h5>Copyrights</h5>
		</div>
	</div>
</footer>
</body>
</html>